# .travis.yml
env:
  global:
    - COVERALLS_REPO_TOKEN=AME7sDQ3lHLAcrrAkWUNWb4CIjZBTbehF
    - CI_NAME=travis-ci
matrix:
  - language: node_js
    node_js:
        -  "5"
    before_install:
        - npm install mocha -g
        - cd ./Platforms/NodeJS-MQTT/
        - npm install
    script:
        - npm test
